FROM nginx:alpine

MAINTAINER duongtv <duongtavan94@gmail.com>

ENV BUILD_PACKAGES="curl-dev bash" \
    LANG=ja_JP.UTF-8 \
    APP_ROOT=/usr/src/app

### set timezone ###########################

RUN apk --update add tzdata && \
    cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
    apk del tzdata && \
    rm -rf /var/cache/apk/*

############################################

### install packages #######################

RUN apk update && \
    apk upgrade && \
    apk add --update $BUILD_PACKAGES && \
    rm -rf /var/cache/apk/* && \
    mkdir -p $APP_ROOT

############################################

### set nginx.conf #########################

RUN rm -f /etc/nginx/conf.d/*
COPY nginx.conf /etc/nginx/conf.d/

############################################

WORKDIR $APP_ROOT
COPY ./public ${APP_ROOT}/public

EXPOSE 80 443
CMD [ "nginx", "-g", "daemon off;" ]
