# .github/workflows/main.yaml
name: Main

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: AutoModality/action-clean@v1
  specs:
    name: CI
    runs-on: ubuntu-18.04

    # If you need DB like MySQL then define service below.
    # Example for PostgreSQL and Redis can be found here:
    # https://github.com/actions/example-services/tree/master/.github/workflows
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test_db
        ports:
          - 3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix
    strategy:
      fail-fast: false
      matrix:
        # Set N number of parallel jobs you want to run tests on.
        # Use higher number if you have slow tests to split them on more parallel jobs.
        # Remember to update ci_node_index below to 0..N-1
        ci_node_total: [5]
        # set N-1 indexes for parallel jobs
        # When you run 2 parallel jobs then first job will have index 0, the second job will have index 1 etc
        ci_node_index: [0, 1, 2, 3, 4]
        ruby:
          - '3.0.1'
        include:
          - ruby: '3.0.1'
            coverage: 'true'

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Ruby 3.0.1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.1
        bundle-cache: true

    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Verify MySQL connection from host
      run: |
        sudo apt-get install -y mysql-client libmysqlclient-dev
        mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -uroot -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY ''; FLUSH PRIVILEGES;"
        mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -uroot -e "ALTER USER 'root'@'172.18.0.1' IDENTIFIED WITH mysql_native_password BY ''; FLUSH PRIVILEGES;"

        mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -uroot mysql

    - name: Bundle Install and Create DB
      run: |
        gem install bundler --version 2.2.29 --no-document
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3 --path vendor/bundle

    - name: Run database
      env:
        RAILS_ENV: test
        # tell Rails to use proper port for MySQL
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
      run: |
        # create DB for Rails 6.x
        bin/rails db:prepare

    - name: Run tests
      env:
        DB_PORT: ${{ job.services.mysql.ports[3306] }} # get randomly assigned published port
        RAILS_ENV: test
      run: |
