name: Main

on: [push]

jobs:
  specs:
    name: CI
    runs-on: ubuntu-latest

    # If you need DB like MySQL then define service below.
    # Example for PostgreSQL and Redis can be found here:
    # https://github.com/actions/example-services/tree/master/.github/workflows
    services:
      # How to use MySQL
      mysql:
        image: mysql:5.7
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DB: food_diary_test
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root
        ports:
        - "3306:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - name: Clean
      uses: AutoModality/action-clean@v1

    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Set up Ruby 3.0.1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.1
        bundler: default
        bundler-cache: true

    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Verify MySQL connection from host
      run: |
        sudo apt-get install -y mysql-client libmysqlclient-dev
        mysql --host 127.0.0.1 --port 3306 -uroot -proot -e "SHOW GRANTS FOR 'root'@'localhost'"
        mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql --host 127.0.0.1 --port 3306 -uroot -proot mysql

    - name: Bundle Install and Create DB
      env:
        RAILS_ENV: test
      run: |
        gem install bundler --version 2.2.29
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3 --path vendor/bundle

    - name: Create DB
      env:
        RAILS_ENV: test
        MYSQL_PORT: 3306
        MYSQL_PASSWORD: root
      run: |
        sudo service mysql start
        bin/rails db:prepare

    - name: Run tests
      env:
        RAILS_ENV: test
        MYSQL_PORT: 3306
        MYSQL_PASSWORD: root
      run: |
        bundle exec rubocop
        bundle exec brakeman
        bundle exec rspec
